services:
  gpu-service:
    image: elainasuki/other:isaac
    container_name: isaac
    environment:
      - DISPLAY=${DISPLAY}
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
      - ACCEPT_EULA=Y
      # - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      # - ROS_LOCALHOST_ONLY=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/isaac-sim/.Xauthority
      - /dev:/dev
      - ./..:/home/Elaina/isaac
      # 挂载缓存目录
      - ./../cache/cache/main:/isaac-sim/.cache
      - ./../cache/cache/computecache:/isaac-sim/.nv/ComputeCache
      - ./../cache/data:/isaac-sim/.local/share/ov/data
    runtime: "nvidia"
    tty: true
    network_mode: "host"
    user: 'Elaina'
    privileged: true
    stdin_open: true
    working_dir: "/home/Elaina/isaac" # 指定默认工作目录
    entrypoint: [ "sh", "-c", "sudo chown Elaina /isaac-sim && zsh" ]
